### ISSUE TITLE
Duplicate channel names

### ISSUE THREAD

**Issue by glaure** [DEWETRON/pyDmdReader#5]
have an issue with a series of files (*.dmd) from the lab team…

I got an error by importing the file content in python through following command (I simplified it for discussion…):
 
```python
    import pyDmdReader
    filename = Path(testfile)
    dmd_file = pyDmdReader.DmdReader(str(filename))
```

“KeyError: 'Duplicate channel name: P_DC'”
 
The guy confirmed that he has this duplicate chanel…

Do I have a possibility to get the data in python anyway through a command like rename_duplicates or delete_duplicates or…?

Or should be exported in another format?

Thank you very much.

**Comment by matthiasstraka** [comment]
Currently, every channel name needs to be unique since we reference channels by name within the python library. As a quick workaround, it is possible to change
https://github.com/DEWETRON/pyDmdReader/blob/2c46e4a9a02edd72820431099a28021d7ae095c2/pyDmdReader/_dmd_reader.py#L306-L307
to
```python
if ch_config.name in channels: 
     continue
```
to simply skip any duplicate channel. The first channel can be used without problems then.
